name: Check that licenses are up-to-date
description: "Generates licenses for this repo and verifies that no diffs exist"
inputs:
  github-token:
    description: 'Token for GH API access'
    required: true
  ssh-key:
    description: 'SSH key that allows checking out xv_dev_tools'
    required: true
  path-repo:
    description: 'Path where xv_dev_tools should be checked out'
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout xv_dev_tools
      uses: actions/checkout@v4
      with:
        repository: xvpn/xv_dev_tools
        token: ${{ inputs.ssh-key }}
        path: xv_dev_tools

    - name: Move dev tools
      shell: bash
      run: |
        pwd
        ls $GITHUB_WORKSPACE
        mv $GITHUB_WORKSPACE/xv_dev_tools ${{ inputs.path-repo }}

    - name: Generate licenses
      shell: bash
      env:
        XV_LICENSE_TOOL_GITHUB_TOKEN_AUTH: ${{ inputs.github-token }}
      run: |
        echo "Path to my-tools: $GITHUB_WORKSPACE"
        ls $GITHUB_WORKSPACE
        ls ${{ inputs.path-repo }}
        cd ${{ inputs.path-repo }}/xv_dev_tools/apps_common
        make dev
        . venv/bin/activate
        # Run a second time as indicated on
        # https://github.com/xvpn/xv_dev_tools/tree/master/apps_common#setting-up-the-tools-locally
        make dev
        cd -
        xv-license-tool --generate
        # Remove debris generated by the tool
        rm -rf $GITHUB_WORKSPACE/xv_apps_common
    - uses: actions/upload-artifact@v3
      with:
        name: acknowledgements
        path: acknowledgements
        if-no-files-found: error
    - uses: ./.github/actions/check-git-working-tree-is-clean