name: Build Website Android
on: [workflow_call]
jobs:
  build:
    name: Generate APK
    env:
      GITHUB_USERNAME: ${{ secrets.USERNAME_GITHUB }}
      GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Gradle rights
        run: chmod +x gradlew
      - name: Assemble 'noinappRelease' with Gradle
        run: ./gradlew assembleNoinappRelease
      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/noinapp/release
          signingKeyBase64: ${{ secrets.SIGNING_WEB_KEYSTORE }}
          alias: ${{ secrets.SIGNING_WEB_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_WEB_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_WEB_KEY_PASSWORD }}
        env:
          # override default build-tools version (33.0.0) -- optional
          BUILD_TOOLS_VERSION: "34.0.0"
      - run: echo "Build status report=${{ job.status }}."
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: pia-output
          path: ${{steps.sign_apk.outputs.signedReleaseFile}}
          if-no-files-found: error