name: Build Playstore Android
on: [workflow_call]
jobs:
  build:
    name: Generate App Bundle
    env:
      GITHUB_USERNAME: ${{ secrets.USERNAME_GITHUB }}
      GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Gradle rights
        run: chmod +x gradlew
      - name: Bundle 'googleRelease' with Gradle
        run: ./gradlew bundleGoogleRelease
      - name: Sign AAB
        id: sign_aab
        uses: ilharp/sign-android-release@v2
        with:
          releaseDir: app/build/outputs/bundle/googleRelease
          signingKey: ${{ secrets.SIGNING_PLAYSTORE_KEYSTORE }}
          keyAlias: ${{ secrets.SIGNING_PLAYSTORE_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_PLAYSTORE_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_PLAYSTORE_KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
      - run: echo "Build status report=${{ job.status }}."
      - name: Upload App Bundle
        uses: actions/upload-artifact@v4
        with:
          name: pia-output-google-play
          path: ${{steps.sign_aab.outputs.signedFile}}
          if-no-files-found: error