name: Build Meta Android
on: [workflow_call]
jobs:
  build:
    name: Generate APK
    env:
      GITHUB_USERNAME: ${{ secrets.USERNAME_GITHUB }}
      GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Gradle rights
        run: chmod +x gradlew

      - name: Assemble 'metaRelease' with Gradle
        run: ./gradlew assembleMetaRelease

      - name: Sign APK
        id: sign_apk
        uses: ilharp/sign-android-release@v2
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        with:
          releaseDir: app/build/outputs/apk/meta/release
          signingKey: ${{ secrets.SIGNING_WEB_KEYSTORE }}
          keyAlias: ${{ secrets.SIGNING_WEB_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_WEB_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_WEB_KEY_PASSWORD }}
          buildToolsVersion: "34.0.0"

      - run: echo "Build status report=${{ job.status }}."

      - name: Upload APK
        uses: actions/upload-artifact@v6
        with:
          name: pia-output-meta
          path: ${{ steps.sign_apk.outputs.signedFile }}
          if-no-files-found: error