name: Google Debug Unit Tests

on:
  push:

permissions:
  contents: read
  pull-requests: read

jobs:
  #1
  unit-tests:
    #2
    runs-on: ubuntu-latest
    #3
    steps:
      - name: Set credentials?
        uses: de-vri-es/setup-git-credentials@v2
        with:
          credentials: ${{ secrets.CREDENTIALS }}
      #4
      - name: Checkout the code
        uses: actions/checkout@v2.6.0
        with:
          token: ${{ secrets.TOKEN }}
      #5
      - name: Setup JAVA 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
      #6
      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
      #7
      - name: Run GoogleDebugUnitTests
        run: ./gradlew testGoogleDebugUnitTest
