name: Build & Publish FDroid APK

on:
  push:
    tags:
      - '*'

jobs:
  Gradle:
    env:
      GITHUB_USERNAME: ${{ secrets.USERNAME_GITHUB }}
      GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: setup jdk
        uses: actions/setup-java@v4
        with:
          java-version: 17
      - name: Make Gradle executable
        run: chmod +x ./gradlew
      - name: Build Release APK
        run: ./gradlew assembleNoinappRelease
      - name: Sign APK
        id: sign_apk
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/apk/noinapp/release
          signingKeyBase64: ${{ secrets.SIGNING_WEB_KEYSTORE }}
          alias: ${{ secrets.SIGNING_WEB_KEY_ALIAS }}
          keyStorePassword: ${{ secrets.SIGNING_WEB_STORE_PASSWORD }}
          keyPassword: ${{ secrets.SIGNING_WEB_KEY_PASSWORD }}
      - name: Releasing using Hub
        uses: kyze8439690/action-release-releaseapk@master
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
          APP_FOLDER: app