name: Build & Publish FDroid APK

on:
  push:
    tags:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  Gradle:
    env:
      GITHUB_USERNAME: ${{ secrets.USERNAME_GITHUB }}
      GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleNoinappRelease

      - name: Decode keystore
        run: echo "${{ secrets.SIGNING_WEB_KEYSTORE }}" | base64 -d > keystore.jks

      - name: Sign APK
        id: sign_apk
        run: |
          $ANDROID_HOME/build-tools/34.0.0/apksigner sign \
            --ks keystore.jks \
            --ks-pass pass:"${{ secrets.SIGNING_WEB_STORE_PASSWORD }}" \
            --key-pass pass:"${{ secrets.SIGNING_WEB_KEY_PASSWORD }}" \
            --ks-key-alias "${{ secrets.SIGNING_WEB_KEY_ALIAS }}" \
            --out app-noinapp-release-signed.apk \
            app/build/outputs/apk/noinapp/release/app-noinapp-release-unsigned.apk

      - name: Releasing using Hub
        uses: kyze8439690/action-release-releaseapk@v1
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
          APP_FOLDER: app